services:
  xgc2-build-focal-base:
    image: ghcr.io/lxk36/xgc2-app-store/xgc2-build-focal-base:1.0.0
    container_name: ${CONTAINER_NAME}
    working_dir: /work
    volumes:
      - ${PWD}:/work
    stdin_open: true
    tty: true
    command: ["bash"]
    healthcheck:
      test: ["CMD", "/usr/local/bin/xgc2-build-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 2
