key: xgc2-build-jammy-full-humble
name: XGC2 jammy humble CI full
version: 1.0.0
image: ghcr.io/lxk36/xgc2-app-store/xgc2-build-jammy-full-humble:1.0.0
dependsOnApp: xgc2-build-jammy-ros-humble
description: Ubuntu jammy + official ROS humble full CI image including simulation and vision stacks. No XGC2 APT packages.
type: build
buildLayer: full
tags:
  - Build
  - CI
  - Jammy
  - Humble
architectures:
  - amd64
  - arm64/v8
license: Apache-2.0
source: https://github.com/lxk36/xgc2-app-store
entrypoints:
  shell: /bin/bash
  healthcheck: /usr/local/bin/xgc2-build-healthcheck
